channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.6
  - numpy==1.23.4
  - scipy<=1.8
  - pandas<=1.3.4
  - statsmodels<=0.13.1
  - nilearn==0.8.1
  - nibabel==3.2.1
  - seaborn==0.11.2
  - scikit-learn==1.1.3
  - ptitprince==0.2.5
  - cmcrameri==1.4
  - notebook
  - pip
  - pip:
    - abagen==0.1.3
    - brainsmash==0.11.0
    - pycortex==1.2.3
    - netneurotools==0.2.3
    - yellowbrick==1.4
    - siibra==0.3a26
    - palettable==3.3.0
    - neuromaps==0.0.3